export default {
  first: [
    'Michael', 'Sarah', 'John', 'Mary', 'David', 'Grace', 'James', 'Esther', 'Daniel', 'Ruth', 'Joseph', 'Rebecca', 'Hannah', 'Emmanuel', 'Deborah', 'Peter', 'Naomi', 'Moses', 'Samuel', 'Paul', 'Elizabeth', 'Benjamin', 'Joshua', 'Victoria', 'Isaac', 'Rory', 'Rachel', 'Matthew', 'Andrew', 'Stephen', 'Martha', 'Philip', 'Ruth', 'Lydia', 'Simon', 'Thomas', 'Judith', 'Angela', 'Timothy', 'Catherine', 'Jonathan', 'Anna', 'Mark', 'Eve', 'Patrick', 'Miriam', 'Luke', 'Daniel', 'Sophia', 'Chloe', 'Noah', 'Elias', 'Jordan', 'Gabriel', 'Victoria', 'Mark', 'Evelyn', 'Nathan', 'Christina', 'Aaron', 'Irene', 'Jacob', 'Lucy', 'Martin', 'Diana', 'Joel', 'Helena', 'Adam', 'Susanna', 'Henry', 'Fiona', 'Anthony', 'Lillian', 'Christopher', 'Theresa', 'Nicholas', 'Tendo', 'Vincent', 'Joanna', 'Alexander', 'Rosaline', 'Caroline', 'Juliet', 'Edwin', 'Priscilla', 'Cedric', 'Brenda', 'Ezekiel', 'Veronica', 'Jeremiah', 'Anastasia', 'Patrick', 'Florence', 'Caleb', 'Clara', 'Leonard', 'Mabel', 'Ethan', 'Augustin', 'Desmond', 'Imelda', 'Sebastian', 'Angela', 'Elijah', 'Annette', 'Justin', 'Martha', 'Fredrick', 'Beatrice', 'Victor', 'Estelle', 'Eric', 'Ivy', 'Stephen', 'Olive', 'Philip', 'Felix', 'Allan', 'Brandon', 'Patrick', 'Barbara', 'Kenneth', 'Henry', 'Clifford', 'Oliver', 'Oscar', 'Roselyn', 'Brian', 'Margaret', 'Francis', 'Daisy', 'Edgar', 'Gloria', 'Ronald', 'Cecilia', 'Trevor', 'Janet', 'Stanley', 'Rita', 'Ivan', 'Patricia', 'Nigel', 'Stella', 'Treasure', 'Goodluck', 'Precious', 'Patience', 'Comfort', 'Peace', 'Gift', 'Hope', 'Mercy', 'Faith', 'Blessing', 'Victory', 'Joy', 'Happiness', 'Charity', 'Kindness', 'Justice', 'Prosper', 'Divine', 'Miracle', 'Promise', 'Angel', 'Glory', 'Marvel', 'Destiny', 'Star', 'Zion'
  ],
  sur: [
    'Okonkwo', 'Adeyemi', 'Mensah', 'Toure', 'Wanjiru', 'Habte', 'Njoroge', 'Abebe', 'Dlamini', 'Moyo', 'Masuku', 'Tlou', 'Mbongo', 'Ngalula', 'Zombo', 'Samba', 'Eze', 'Obasi', 'Amadi', 'Nwachukwu', 'Oluwole', 'Ademola', 'Folarin', 'Nkosi', 'Zulu', 'Chilufya', 'Mwangi', 'Omari', 'Kagiso', 'Makori', 'Nyongo', 'Adebayo', 'Kamau', 'Ochieng', 'Chikere', 'Baloyi', 'Mulenga', 'Ngoma', 'Kelechi', 'Nyathi', 'Lukwesa', 'Onyango', 'Ndlovu', 'Banda', 'Chioma', 'Ekong', 'Kanyangi', 'Ifeanyi', 'Makena', 'Chisom', 'Ngugi', 'Adichie', 'Bako', 'Mahoro', 'Njenga', 'Oketch', 'Mutua', 'Obiora', 'Sithole', 'Amara', 'Ndidi', 'Olorunfemi', 'Simba', 'Onyeka', 'Anyanwu', 'Chukwuma', 'Ibrahim', 'Olaosebikan', 'Chigozie', 'Ogundele', 'Ekwueme', 'Osei', 'Nkatha', 'Wamukota', 'Chibuzo', 'Luwalira', 'Odongo', 'Amankwa', 'Yeboah', 'Ajayi', 'Egbujo', 'Makokha', 'Njoroge', 'Mbatha', 'Dube', 'Mwenda', 'Obong', 'Tadesse', 'Wakio', 'Mabunda', 'Ngondo', 'Kakembo', 'Asante', 'Mugisha', 'Ayodele', 'Omotosho', 'Chiwenga', 'Onyekachi', 'Oluwatobi', 'Achieng', 'Bukenya', 'Kambale', 'Musoke', 'Muthoni', 'Nzinga', 'Bakari', 'Otieno', 'Fumilayo', 'Uzoamaka', 'Ofili', 'Ochieng', 'Ogugua', 'Adekunle', 'Ekwu', 'Njoku', 'Nkechi', 'Okeke', 'Okafor'
  ],
  company: [
    'Valeria Electromotive',
    'Solari Inc.',
    'Cosmocell',
    'Mizugami HI',
    'Hikari Motors',
    'Informataria',
    'Lyonix',
    'Infra Electronics'
  ],
  companywea: [
    'Rosenthal Point',
    'Viking Arms'
  ],
  companyfoo: [
    'Daiyama',
    'Agrinoria',
    'Weilong Group',
    'Alania Products'
  ],
  companymin: [
    'Valeria Electromotive',
    'INOIl',
    'Gasolux',
    'Energo Group',
    'Friese Energy',
    'Daiyama Dynamics',
    'Forma Gasworks'
  ],
  country: [
    'Marundu',
    'Sorika',
    'Nyambara',
    'Kalendi',
    'Zembira',
    'Bantari',
    'Lokonda',
    'Tasumba',
    'Cassovia',
    'Ladya',
    'Molanga',
    'Biremba',
    'Fazira',
    'Samboka',
    'Kimora',
    'Togawa',
    'Lusanja',
    'Orenda',
    'Dalowa',
    'Zetuba',
    'Tchebanga',
    'Pashogo', 'Bonibia', 'Makora', 'Jandel', 'Kirana', 'Cawana', 'Awenar', 'Tabiri',
    'Zunaba', 'Doomasa', 'Langol', 'Sakara', 'Gisumbi', 'Bikand', 'Zanawi',
    'Ronubbo', 'Danur', 'Elizondo', 'Anassia', 'Nomasa', 'Tarund', 'Ficabia',
    'Balend', 'Nokassa', 'Lamund', 'Nikora', 'Garand', 'Tebuk', 'Zalem',
    'Gosonga',
    'Habunda',
    'Nandek',
    'Vesiro',
    'Daroom',
    'Jabiro',
    'Osolo',
    'Agadio',
    'Fosir',
    'Lumendos',
    'Katya',
    'Moribi',
    'Gonobo',
    'Magola',
    'Gandawi',
    'Codomo',
    'Adash',
    'Lizongo',
    'Hawoono'
  ],
  region: [
    'Marundu',
    'Sorika',
    'Nyambara',
    'Kalendi',
    'Zembira',
    'Bantari',
    'Lokonda',
    'Tasumba',
    'Cassovia',
    'Ladya',
    'Molanga',
    'Biremba',
    'Fazira',
    'Samboka',
    'Kimora',
    'Togawa',
    'Lusanja',
    'Orenda',
    'Dalowa',
    'Zetuba',
    'Tchebanga',
    'Pashogo', 'Bonibia', 'Makora', 'Jandel', 'Kirana', 'Cawana', 'Awenar', 'Tabiri',
    'Zunaba', 'Doomasa', 'Langol', 'Sakara', 'Gisumbi', 'Bikand', 'Zanawi',
    'Ronubbo', 'Danur', 'Elizondo', 'Anassia', 'Nomasa', 'Tarund', 'Ficabia',
    'Balend', 'Nokassa', 'Lamund', 'Nikora', 'Garand', 'Tebuk', 'Zalem',
    'Gosonga',
    'Habunda',
    'Nandek',
    'Vesiro',
    'Daroom',
    'Jabiro',
    'Osolo',
    'Agadio',
    'Fosir',
    'Lumendos',
    'Katya',
    'Moribi',
    'Gonobo',
    'Magola',
    'Gandawi',
    'Codomo',
    'Adash',
    'Lizongo',
    'Hawoono'
  ]
}
